title: Rakhim.org
description: >
    I'm Rakhim: a programmer, teacher, writer and podcaster.
author: Rakhim Davletkaliyev
email: contact@rakhim.org
baseurl: ""
url: "https://rakhim.org"
twitter_username: freetonik
github_username: freetonik

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
