baseurl = "https://rakhim.org"
languageCode = "en-us"
title = "Rakhim.org"
theme = "ra"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

pygmentsCodeFences = true
pygmentsStyle = "emacs"

[permalinks]
    blog = "/:filename/"
    honestly-undefined = "/:section/:slug/"

[markup.goldmark.renderer]
    unsafe= true

[params]
    description = "Blog of Rakhim D., a programmer, teacher, writer and podcaster."
    descriptionhu = "A webcomic about computers and uncertainty"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Courses"
    url = "https://learn.codexpanse.com/collections"
    weight = 3
[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 4
[[menu.main]]
    name = "Bookshelf"
    url = "/bookshelf"
    weight = 9
[[menu.main]]
    name = "YTube"
    url = "https://www.youtube.com/c/codexpanse"
    weight = 6
[[menu.main]]
    name = "Comics"
    url = "/honestly-undefined"
    weight = 6
[[menu.main]]
    name = "EmacsCast"
    url = "https://emacscast.org"
    weight = 7
[[menu.main]]
    name = "Twttr"
    url = "https://twitter.com/freetonik"
    weight = 10
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"
