baseurl = "https://rakhim.org"
languageCode = "en-us"
title = "Rakhim's homepage"
theme = "ra"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

pygmentsCodeFences = true
pygmentsStyle = "emacs"

[permalinks]
    blog = "/:filename/"
    honestly-undefined = "/:section/:slug/"

[markup.goldmark.renderer]
    unsafe= true
    hardWraps = true

[params]
    description = "Blog of Rakhim D., a programmer, teacher, writer and podcaster."
    descriptionhu = "A webcomic about computers and uncertainty"

[[menu.main]]
    name = "Home"
    pageref="/"
    url = "/"
    weight = 10

[[menu.main]]
    name = "Blog"
    url = "https://rakhim.exotext.com/"
    weight = 12

[[menu.main]]
    name = "Talks"
    url = "/talks"
    pageref = "talks"
    weight = 13

[[menu.main]]
    name = "Github"
    url = "https://github.com/freetonik/"
    weight = 75
[[menu.main]]
    name = "Bluesky"
    url = "https://bsky.app/profile/rakhim.org"
    weight = 80
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/rdavletkaliyev/"
    weight = 81
