baseurl = "https://rakhim.org"
languageCode = "en-us"
title = "Rakhim.org"
theme = "ra"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

pygmentsCodeFences = true
pygmentsStyle = "emacs"

[permalinks]
    blog = "/:filename/"
    honestly-undefined = "/:section/:slug/"

[markup.goldmark.renderer]
    unsafe= true
    hardWraps = true

[params]
    description = "Blog of Rakhim D., a programmer, teacher, writer and podcaster."
    descriptionhu = "A webcomic about computers and uncertainty"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Blog"
    url = "https://blog.rakhim.org"
    weight = 11
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 12
[[menu.main]]
    name = "Courses"
    url = "https://codexpanse.com"
    weight = 20
[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 30
[[menu.main]]
    name = "Comics"
    url = "/honestly-undefined"
    weight = 40
[[menu.main]]
    name = "Bookshelf"
    url = "/bookshelf"
    weight = 50
[[menu.main]]
    name = "YT"
    url = "https://www.youtube.com/c/codexpanse"
    weight = 70
[[menu.main]]
    name = "TW"
    url = "https://twitter.com/freetonik"
    weight = 80
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"
