[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.47.1"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.47.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/feed.xml"
  to = "/index.xml"

[[redirects]]
  from = "/2018/09/i-no-longer-care-about-og-tags-twitter-cards-etc./"
  to = "/2018/09/i-no-longer-care-about-og-tags-twitter-cards-etc/"

[[redirects]]
  from = "/archive"
  to = "/"
